server:
  http_listen_port: 9080
  grpc_listen_port: 9095

positions:
  filename: C:\Promtail\positions.yaml

clients:
  - url: http://192.168.22.35:3100/loki/api/v1/push

scrape_configs:
  - job_name: windows_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: windows
          __path__: C:\Windows\System32\winevt\Logs\*.evtx